services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-admin}
    ports:
      - "15672:15672"
      - "5672:5672"

  mongo:
    image: mongo:7.0.3
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data/db:/data/db

  redis:
    image: redis:7.4-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data

  lgtm:
    image: grafana/otel-lgtm:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
